name: Find libs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Check libs
      run: |
        sudo apt-get update
        sudo apt-get install -y libavcodec-dev libavformat-dev libavutil.dev
        sudo ls /usr/local/lib/
        sudo find / -name 'libavcodec.so*'
        sudo find / -name 'libavformat.so*'
        sudo find / -name 'libavutil.so*'